### ISSUE TITLE
Implement HTTP caching

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/architecture#35]
In order to optimize performance between the streamer and other modules, we must make sure that the streamer implements proper HTTP caching.

A best practice document is available to summarize how the streamer should handle HTTP caching for the manifest, resources and APIs: https://github.com/readium/readium-2/blob/master/streamer/server/caching.md

**Comment by HadrienGardeur** [comment]
This has already been handled in Go, we need to add issues and support for this in both Java and Swift implementations.

**Comment by danielweck** [comment]
This is implemented in NodeJS too.
https://github.com/edrlab/r2-streamer-js
