### ISSUE TITLE
Streamer Media Overlays, SMIL files with interspersed par and seq elements

### ISSUE THREAD

**Issue by danielweck** [readium/architecture#37]
@HadrienGardeur 
https://github.com/readium/r2-streamer-go/blob/master/parser/epub/smil.go#L7
```go
type Body struct {
	TextRef string `xml:"textref,attr"`
	Seq     []Seq  `xml:"seq"`
	Par     []Par  `xml:"par"`
}

type Seq struct {
	TextRef string `xml:"textref,attr"`
	Par     []Par  `xml:"par"`
	Seq     []Seq  `xml:"seq"`
}
```

This breaks with SMIL files such as (the order of interspersed `seq` and `par` elements is important):
```xml
<smil>
    <body>
        <seq>
            <par>
           ....    
            </par>
            <seq>
            ....
            </seq>
            <par>
           ....    
            </par>
        </seq>
        <par>
        ....
        </par>
    </body>
</smil>
```

I addressed this in the NodeJS implementation by making sure `body` extends `seq`, and `seq` has a sorted `children` list, which items are either `seq` (recursive) or `par`:
https://github.com/edrlab/r2-streamer-js/blob/develop/src/parser/epub/smil-body.ts#L14
https://github.com/edrlab/r2-streamer-js/blob/develop/src/parser/epub/smil-seq.ts#L16
https://github.com/edrlab/r2-streamer-js/blob/develop/src/parser/epub/smil-par.ts#L18

**Comment by HadrienGardeur** [comment]
Thanks, I understand better now, I thought that you were talking about the model that we use for the Web Publication Manifest.

cc @banux

**Comment by HadrienGardeur** [comment]
Can we close this issue? cc @danielweck
