### ISSUE TITLE
Use absolute URIs in the streamer

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/architecture#38]
As a follow-up to #36 we're moving away from using paths relative to the OPF in the streamer.

We'll now stictly use absolute paths based on the root of the container instead.

The following resource types that we parsed are affected:

- OPF
- Navigation Document
- NCX
- SMIL

While `encryption.xml` parsing is not as directly affected by this change, we need to make sure that we still match resources correctly after this change.

In the streamer, we should now have absolute URIs in the following elements:

- `spine`
- `resources`
- all ToC collections (`toc`, `landmarks`, `loi`, `page-list`, ...)
- media overlay APIs

**Comment by danielweck** [comment]
I implemented this a while back in `r2-streamer-js` (i.e. the unambiguous full path relative to the root of the EPUB container is used internally, as well as in the `resource` query string parameter of media-overlays templated URIs).
I also recently ensured that full absolute HTTP URLs are only generated in the pretty-printed version of web pub manifest, see this comment:
https://github.com/readium/readium-2/issues/40#issuecomment-306721481

**Comment by camill-a** [comment]
The Swift streamer now use absolute URIs. See PR Fix/absolute_uri #41.

**Comment by HadrienGardeur** [comment]
Closing this issue, it shouldn't be in our main repo anymore.
