### ISSUE TITLE
Code review strategy

### ISSUE THREAD

**Issue by aslagle** [readium/architecture#51]
This issue is for discussing code review strategy for readium 2 and the process for migrating existing projects from other organizations to the readium github org.

To start the discussion, I'd say that once a project is ready for production use all changes must be reviewed by another developer before being merged or released. Reviewers should check that the code is documented and tested as well. Ideally the reviewers should be other developers working on the same project, but if no one is available any readium developer may do a review.

For something that's still a prototype and not ready to be used by others, it's fine for developers to manage the project however they prefer. That said, it's nice to get early feedback from others who might use a project later - I'd have liked us to do more of that for the TypeScript projects particularly.

I'm not sure how this should relate to migrating projects into the readium github org.

**Comment by mickael-menu** [comment]
This was addressed in this document: https://readium.org/development/contributing/
