### ISSUE TITLE
Locator 'fragment' and 'href' which includes its own URI "fragment"

### ISSUE THREAD

**Issue by danielweck** [readium/architecture#92]
See:
https://github.com/readium/architecture/commit/f90b440dc3aa63c59981e3e46a7db7b8a545c613#r33122380

`href` is a JSON Schema `uri-reference`, which may contain its own URI "fragment". What would the processing model of the `fragment` property be in this case?
Example of a `locator` object (intentionally idiosyncratic, and admittedly idiotic ... but this is just to emphasise the point ;)
```json
{
  "href": "http://example.com/book/chapter.html#para1",
  "type": "text/html",
  "locations": {
    "fragment": "#cfi(/2/4/6)"
  }
}
```

**Comment by danielweck** [comment]
Spec: https://github.com/readium/architecture/blob/master/locators/README.md#fragments

**Comment by HadrienGardeur** [comment]
This was added in the doc but there's no easy way to express this information in the JSON Schema
