### ISSUE TITLE
Locator without 'locations' (e.g. no 'fragment') but with 'href' URI "fragment"?

### ISSUE THREAD

**Issue by danielweck** [readium/architecture#93]
See:
https://github.com/readium/architecture/commit/f90b440dc3aa63c59981e3e46a7db7b8a545c613#r33122288

The `locations` property of a `locator` object is currently not required, which means that this is a valid use-case? (what is the intent for a "location-less" locator?)
```json
{
  "href": "http://example.com/book/chapter.html",
  "type": "text/html"
}
```

...is this because the `href` URI may contain its own "fragment"?
```json
{
  "href": "http://example.com/book/chapter.html#para1",
  "type": "text/html"
}
```

**Comment by danielweck** [comment]
Spec: https://github.com/readium/architecture/blob/master/locators/README.md#fragments

**Comment by HadrienGardeur** [comment]
> The `locations` property of a `locator` object is currently not required, which means that this is a valid use-case? (what is the intent for a "location-less" locator?)

For a CBZ or a FXL document, just knowing the `href` might work although it's a bit lacking context-wise.

> ...is this because the `href` URI may contain its own "fragment"?

That's something that we should recommend against using. We want to make it easy for an app to match these `href` with similar `href` in a `readingOrder`.

**Comment by danielweck** [comment]
Doh, of course bookmarks for FXL publications usually consist in `href` only.
